### ISSUE TITLE
Add measurement unit for distance in docs

### ISSUE THREAD

**Issue by mraxus** [tomayac/local-reverse-geocoder#12]
Hello, love the project.

For clarity, please add the unit that is used for the `distance` data field in the response.

**Comment by tomayac** [comment]
@mraxus Thanks for the Issue. I have addressed it with https://github.com/tomayac/local-reverse-geocoder/commit/6675881c03eda2ae4a6b9e96c65c5ce6735ffa82. Hope it's all clear now :-)
