### ISSUE TITLE
missing npm rename

### ISSUE THREAD

**Issue by davidjludwig** [tomayac/local-reverse-geocoder#14]
please review the npm dependencies -- after i did "npm install rename" this error (below) went away.

Unzipped GeoNames alternate names data
fs.js:809
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

Error: ENOENT: no such file or directory, rename

**Comment by tomayac** [comment]
Thanks for the report. Currently on vacation, will look at the Issue when I return.

**Comment by davidjludwig** [comment]
i don't think it will matter, but just in case, here is some system info:

$ npm -v
4.3.0
$ node -v
v6.9.1
$ uname -a
Darwin 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64

**Comment by tomayac** [comment]
Sorry, I can't reproduce this. If you still encounter this issue, please comment and I am happy to reopen the issue. Also, apologies for the ridiculously long turn-around time :-(
