### ISSUE TITLE
Crash when replacing yesterday's geodata (Extract.writer.error [Error: ENOENT: no such file or directory, lstat '/tmp/geonames/cities/cities1000.txt'])

### ISSUE THREAD

**Issue by tkafka** [tomayac/local-reverse-geocoder#39]
### Reproduction steps:
1. Run `local-reverse-geocoder`, let it create files with dates in name (eg. `cities/cities1000_2021-03-19.txt`)
2. Wait another day (or rename file to older date, eg. `cities/cities1000_2021-03-19.txt` → `cities/cities1000_2021-03-15.txt`)
3. Start `local-reverse-geocoder` again.

### What I expected:
Geocoder updates its files.

### What actually happens
Geocoder crashes with `Extract.writer.error [Error: ENOENT: no such file or directory, lstat '/tmp/geonames/cities/cities1000.txt']`.

The cause is this:
- we call [unzip.Extract](https://github.com/tomayac/local-reverse-geocoder/blob/40f591edbfe138ff27251ebd2ed9304fdbb27ed2/index.js#L466)
- Extract extracts files from downloaded zip into a folder and emits [close](https://github.com/tomayac/local-reverse-geocoder/blob/40f591edbfe138ff27251ebd2ed9304fdbb27ed2/index.js#L467)
- We [rename](https://github.com/tomayac/local-reverse-geocoder/blob/40f591edbfe138ff27251ebd2ed9304fdbb27ed2/index.js#L468) and [unlink](https://github.com/tomayac/local-reverse-geocoder/blob/40f591edbfe138ff27251ebd2ed9304fdbb27ed2/index.js#L477)
- Extract uses `fstream` module, and it calls `stat` on extracted file *after calling close* - see [code](https://github.com/npm/fstream/blob/42354590e23bb514eb5c869eea64406be2947c6c/lib/writer.js#L269)!
- Calling `stat` on now nonexistent file causes crash (error is emitted from fstream, and not handled by anyone).

### Fix ideas:
1. Fix the underlying stream libs ([fstream](https://github.com/npm/fstream) shouldn't [touch the extracted file](https://github.com/npm/fstream/blob/42354590e23bb514eb5c869eea64406be2947c6c/lib/writer.js#L269) after it passes `close` event)
2. Ignore `error` event from `unzip.Extract`
```
extractStream
          .on('error', function (err) {
            if (err.code === 'ENOENT') {
              // ignore - fstream writer runs stat/lstat after extract is finished (and .close sent), and it crashes, because we have already used and moved/deleted it's file
            } else {
              throw err
            }
          })
```
3. Use unzip to extract just a single file we need, in memory, without writing to disk
4. Keep the extracted file (eg. cities1000.txt), so that we allow fstream to touch it however it wants after the extraction.

### Beware:
All `_get*data` methods have this problem, it needs to be fixed everywhere.

**Comment by tkafka** [comment]
It is very curious that no one has reported this before, as it happens every time you don't clean up the data and restart local-reverse-geocoder. I may have discovered it by moving `dumpDirectory` to `/tmp/geonames` (which I believe should be a default place, the geo database shouldn't be just dumped inside node_modules).

**Comment by tomayac** [comment]
I think what you're asking for is making [`GEONAMES_DUMP`](https://github.com/tomayac/local-reverse-geocoder/blob/40f591edbfe138ff27251ebd2ed9304fdbb27ed2/index.js#L95) user-configurable. I'm happy to merge a PR that adds this.

**Comment by tkafka** [comment]
@tomayac Hi Thomas, that was already configurable - see [here](https://github.com/tomayac/local-reverse-geocoder/blob/40f591edbfe138ff27251ebd2ed9304fdbb27ed2/index.js#L658).

I dived into the error with streams, but I think that the real problem is that one of `node-unzip-2`, `fstream`, or their interactions is wrongly written. However, there was no need to actually store the unzipped files on a disk, so I forked `local-reverse-geocoder` to https://github.com/tkafka/local-reverse-geocoder and rewrote it to use `unzip-stream` to extract the wanted file from stream to disk.

See https://github.com/tkafka/local-reverse-geocoder/commit/6e9650062678610b20f400697c945d19bf0323b2

**Comment by tomayac** [comment]
> @tomayac Hi Thomas, that was already configurable - see [here](https://github.com/tomayac/local-reverse-geocoder/blob/40f591edbfe138ff27251ebd2ed9304fdbb27ed2/index.js#L658).

Oh, sorry. It's been a while that I touched this code. 

> I dived into the error with streams, but I think that the real problem is that one of `node-unzip-2`, `fstream`, or their interactions is wrongly written. However, there was no need to actually store the unzipped files on a disk, so I forked `local-reverse-geocoder` to https://github.com/tkafka/local-reverse-geocoder and rewrote it to use `unzip-stream` to extract the wanted file from stream to disk.

Thanks for working on this, but…

> See [tkafka@6e96500](https://github.com/tkafka/local-reverse-geocoder-2/commit/6e9650062678610b20f400697c945d19bf0323b2)

…I wonder why you went for forking this. I am and always was happy to merge PRs. I'd be happy to add you to the [list of contributors](https://github.com/tomayac/local-reverse-geocoder#contributors).

**Comment by tkafka** [comment]
@tomayac Please don't take it personally, I just needed it fixed quickly. I just created a pull request https://github.com/tomayac/local-reverse-geocoder/pull/40.
