### ISSUE TITLE
.lookup() has issues if you call more than once before it has cached all geoNames data

### ISSUE THREAD

**Issue by chriskinsman** [tomayac/local-reverse-geocoder#4]

**Comment by chriskinsman** [comment]
Easily fixed by manually calling _init() prior to wiring it up to an EventEmitter.  Feels a little hinky calling an implied private method but can't think of an easy way to maintain the lazy loading behavior of lookUp that will work when you have parallel calls to lookUp...

**Comment by tomayac** [comment]
Seems like you fixed this yourself :-) in https://github.com/tomayac/local-reverse-geocoder/pull/6. Thanks!
