### ISSUE TITLE
Geoname dump is returning 404

### ISSUE THREAD

**Issue by FrikkieSnyman** [tomayac/local-reverse-geocoder#43]
It seems like https://download.geonames.org/export/dump/ is returning a 404 since this morning. Any idea if this is being addressed, or some place where we can monitor progress?

**Comment by FrikkieSnyman** [comment]
It's back up again, it seems

**Comment by tomayac** [comment]
Thanks for confirming it's up again. It was apparently a glitch on Geonames' end.
