### ISSUE TITLE
Referencing undefined `options.countries` when not explicitly initialized

### ISSUE THREAD

**Issue by peterwanggg** [tomayac/local-reverse-geocoder#47]
Hi, thanks for this great library.

I got an error when following the usage code snippet without calling `init`. I fixed this locally by adding a check for `options.countries === undefined` to the if statement on [line 646 of index.js](https://github.com/tomayac/local-reverse-geocoder/blob/main/index.js#L646).

**Comment by tomayac** [comment]
Addressed via changing the order and wording in the `README`: https://github.com/tomayac/local-reverse-geocoder/commit/9b98e179f15917e6e142bcfd49b3e224e3d32ae4.

**Comment by peterwanggg** [comment]
@tomayac the same error is thrown if you call `init()` with an empty function

**Comment by tomayac** [comment]
What do you mean by "empty function"?
