### ISSUE TITLE
Suggestion: Move geonames dump to post-install

### ISSUE THREAD

**Issue by aminmahrami** [tomayac/local-reverse-geocoder#53]
Currently, it takes 6 seconds for admin 2 & 3 and 30 seconds for 3 & 4 to dump the geonames before my Express server runs (local machine numbers)

Wouldn't be nicer to move this task to post-install? This way the server wouldn't have to wait for the initialize to finish.

**Comment by tomayac** [comment]
Sounds like a great idea. Are you up for implementing this?

**Comment by itaisatati** [comment]
Hi @aminmahrami, are you working on this?
I'd like to give it a try if you aren't

**Comment by aminmahrami** [comment]
I'm not working on this project anymore, you can go ahead.

**Comment by itaisatati** [comment]
Hi again, @aminmahrami
Please let me know in the PR if it sufficiently addresses your requirements

**Comment by tomayac** [comment]
Fixed via #61.
