### ISSUE TITLE
load from folder

### ISSUE THREAD

**Issue by justekoro** [tomayac/local-reverse-geocoder#55]
hi,
my server seems to not have engough capacities to load the geodump data by itself.
I downloaded it from my computer using `dumpDirectory` property, but **is there a way to load the data from the dumpDirectory folder?**

**Comment by tomayac** [comment]
You can download the data manually and put it in the directory by hand. Also see https://github.com/tomayac/local-reverse-geocoder#a-word-on-data-freshness.
