### ISSUE TITLE
wrong country results being returned unless increase maxResults

### ISSUE THREAD

**Issue by bloodfire91** [tomayac/local-reverse-geocoder#7]
If I search for Busan, South Korea:

    curl "http://localhost:3000/geocode?latitude=35.17955429999999&longitude=129.07564160000004&maxResults=2"

I get the following:

[[{"geoNameId":"PLA","name":"CO","asciiName":null,"alternateNames":"27","latitude":"70001","longitude":null,"featureClass":null,"featureCode":"261187","countryCode":null,"cc2":"211","admin1Code":"America/Bogota","admin2Code":"2016-01-28","admin3Code":null,"admin4Code":null,"population":null,"elevation":null,"dem":null,"timezone":null,"modificationDate":null,"distance":5289.300553794601},{"geoNameId":"2729907","name":"Longyearbyen","asciiName":"Longyearbyen","alternateNames":"Gorad Longjir,LYR,Long'ir,Longijur,Longir,Longjerbiene,Longjir,Longjirbjuen osh,Longjyrbienas,Longjērbīene,Longyearbyen,Longyearbyur,Longyearbýur,Lonqyirbyuen,lang yi er cheng,langayrbyn,langyrbyn,lanyiyarpiyan,long-wiealeubwien,longiri,lwnghyarbyn,lwngyyrbyn,lxng yeiy r beiyn,rongui~erubin,Горад Лонгйір,Лонгийър,Лонгйир,Лонгйирбюен ош,Лонгьир,Лонгїр,Лонгјир,לונגיירבין,لانگایربین,لانگیربین,لونغياربين,லாங்யியர்பியன்,ลองเยียร์เบียน,ლონგირი,ロングイェールビーン,朗伊爾城,롱위에아르뷔엔","latitude":"78.22334","longitude":"15.64689","featureClass":"P","featureCode":"PPLC","countryCode":"SJ","cc2":"NO","admin1Code":{"name":"Svalbard","asciiName":"Svalbard","geoNameId":"7521757"},"admin2Code":{"name":"Spitsbergen","asciiName":"Spitsbergen","geoNameId":"7535696"},"admin3Code":null,"admin4Code":null,"population":"2060","elevation":null,"dem":"1","timezone":"Arctic/Longyearbyen","modificationDate":"2015-03-14","distance":6688.715709465299}]]

None of the above countries are anywhere close to South Korea. However if I increase maxResults to 3 all results are from Busan.

[[{"geoNameId":"1838524","name":"Busan","asciiName":"Busan","alternateNames":"Bousan,Busan,Busan-si,Busán,Fousan,Fusan,Fuzan,PUS,Phu San,Phủ San,Pusan,Pusana,Pusano,Tsau-liang-hai,busan,busangwang-yeogsi,busansi,fu shan,fu shan guang yu shi,fu shan shi,pu san,Μπούσαν,Пусан,ปูซาน,釜山,釜山市,釜山广域市,釜山広域市,부산,부산광역시,부산시","latitude":"35.10278","longitude":"129.04028","featureClass":"P","featureCode":"PPLA","countryCode":"KR","cc2":null,"admin1Code":{"name":"Busan","asciiName":"Busan","geoNameId":"1838519"},"admin2Code":null,"admin3Code":null,"admin4Code":null,"population":"3678555","elevation":null,"dem":"2","timezone":"Asia/Seoul","modificationDate":"2016-02-09","distance":9.12235943037776},{"geoNameId":"1842966","name":"Gijang","asciiName":"Gijang","alternateNames":"Gijang,Kichang,Kicho,Kichō,Kijang,gijang,기장","latitude":"35.24417","longitude":"129.21389","featureClass":"P","featureCode":"PPLA3","countryCode":"KR","cc2":null,"admin1Code":{"name":"Busan","asciiName":"Busan","geoNameId":"1838519"},"admin2Code":null,"admin3Code":null,"admin4Code":null,"population":"43064","elevation":null,"dem":"21","timezone":"Asia/Seoul","modificationDate":"2015-05-06","distance":14.469636723691387},{"geoNameId":"1894035","name":"Ilgwang","asciiName":"Ilgwang","alternateNames":"Ilgwang,ilgwang,일광","latitude":"35.264","longitude":"129.23349","featureClass":"P","featureCode":"PPLA3","countryCode":"KR","cc2":null,"admin1Code":{"name":"Busan","asciiName":"Busan","geoNameId":"1838519"},"admin2Code":null,"admin3Code":null,"admin4Code":null,"population":"0","elevation":null,"dem":"1","timezone":"Asia/Seoul","modificationDate":"2016-03-10","distance":17.139635409200807}]]

I'm having the same issue with Tokyo, Beijing, Juneau (alaska)

**Comment by natanavra** [comment]
This still happens,
My workaround is to retrieve 10 results and search by country name (coupled with Maxmind IP based geolocation for checking the country)

**Comment by tomayac** [comment]
@natanavra I have just released [v0.2.1](https://www.npmjs.com/package/local-reverse-geocoder), all test cases from https://github.com/tomayac/local-reverse-geocoder/issues/7 worked fine.

**Comment by natanavra** [comment]
Hi, just tested with El Salvador using (13.695649, -89.194025), these are the results I get:

```
[ { geoNameId: '4907131',
    name: 'Rantoul',
    asciiName: 'Rantoul',
    alternateNames: 'Rantul,rantwl,Рантул,رانتول,র‌্যান্টুল',
    latitude: '40.30837',
    longitude: '-88.15588',
    featureClass: 'P',
    featureCode: 'PPL',
    countryCode: 'US',
    cc2: null,
    admin1Code: { name: 'Illinois', asciiName: 'Illinois', geoNameId: '4896861' },
    admin2Code: 
     { name: 'Champaign County',
       asciiName: 'Champaign County',
       geoNameId: '4887163' },
    admin3Code: null,
    admin4Code: null,
    population: '12941',
    elevation: '227',
    dem: '229',
    timezone: 'America/Chicago',
    modificationDate: '2011-05-14',
    alternateName: { post: '61866' },
    distance: 2961.5431909968343 },
...```

**Comment by tomayac** [comment]
For http://localhost:3000/geocode?latitude=13.695649&longitude=-89.194025, I get the correct-looking value below:

```json
[
  [{
    "geoNameId": "3583361",
    "name": "San Salvador",
    "asciiName": "San Salvador",
    "alternateNames": "Gorad San-Sal'vador,SAL,Salvador,San Salbador,San Salvado,San Salvador,San Salvadoras,San Salvadori,San Salvadò,San Salwador,San-Sal'vador,San-Salvador,San-Salvadoro,Sansalvadora,Urbs Sancti Salvatoris,can calvator,san salvadwr,san salwadwr,san slfadwr,san-salvadori,sana salavadora,sana salvhadora,sana-salvadora,sansalbadoleu,sansalwadxr,sansarubadoru,sheng sa er wa duo,sn slwwdwr,Σαν Σαλβαδόρ,Горад Сан-Сальвадор,Сан Салвадор,Сан-Сальвадор,Սան Սալվադոր,סאן סאלוואדאר,סן סלוודור,سان سالوادور,سان سالۋادور,سان سلفادور,سان سلواڈور,सान साल्व्हाडोर,सान-साल्वाडोर,ਸਾਨ ਸਾਲਵਾਦੋਰ,சான் சல்வடோர்,ซันซัลวาดอร์,སན་སལ་ཝ་ཌོར།,სან-სალვადორი,ሳን ሳልቫዶር,サンサルバドル,聖薩爾瓦多,산살바도르",
    "latitude": "13.68935",
    "longitude": "-89.18718",
    "featureClass": "P",
    "featureCode": "PPLC",
    "countryCode": "SV",
    "cc2": null,
    "admin1Code": {
      "name": "San Salvador",
      "asciiName": "San Salvador",
      "geoNameId": "3583360"
    },
    "admin2Code": null,
    "admin3Code": null,
    "admin4Code": null,
    "population": "525990",
    "elevation": null,
    "dem": "653",
    "timezone": "America/El_Salvador",
    "modificationDate": "2015-06-04",
    "distance": 1.0185485478765126
  }]
]
```

**Comment by kunokdev** [comment]
So is this relevant? It might lose accuracy in some cases?

**Comment by tomayac** [comment]
@kunokdev I think this is correct, the GeoNames reverse geocoding API delivers the same [result](http://api.geonames.org/extendedFindNearby?lat=13.695649&lng=-89.194025&username=demo) for your points.
