### ISSUE TITLE
Official Docker image

### ISSUE THREAD

**Issue by electriquo** [tomayac/local-reverse-geocoder#72]
**THANK YOU** for local-reverse-geocoder ❤️

There is a documentation of using Docker but I couldn't find any official image.
Is there an official Docker image? If not, what do you think of releasing one?

**Comment by tomayac** [comment]
(Sorry for the slow turn-around time, I was busy with Google I/O Connect.) The file is [in the repo](https://github.com/tomayac/local-reverse-geocoder/blob/main/Dockerfile). I am not familiar with the process to make this more official, but happy for you to take this on.
