### ISSUE TITLE
citiesFileOverride ignored when choosing specific country 

### ISSUE THREAD

**Issue by eligrifel** [tomayac/local-reverse-geocoder#83]
when choosing specific country IL for example  alternateNames: false still return alternateNames and cities dosent work at all  
it dosent download the file and dosent show city on the result like when calling init with no params 
     load: {
            admin1: false,
            admin2: false,
            admin3And4: false,
            alternateNames: false,
          },
          citiesFileOverride:'cities15000',
          countries:['IL']
         
         please try with this settings to test it

**Comment by tomayac** [comment]
When you set the country to Israel, it downloads [`IL.zip`](https://download.geonames.org/export/dump/IL.zip) in the background, which can't be refined further. You need to live with whatever is in this file, or download more data and then have more fine-grained control. Sorry, I don't think there's a better solution.
