### ISSUE TITLE
when chossing specific country result are wrong  

### ISSUE THREAD

**Issue by eligrifel** [tomayac/local-reverse-geocoder#84]
asciiName is completely different 

with specific country  
[
    {
      "geoNameId": "293775",
      "name": "Ramat Tiomkin",
      "asciiName": "Ramat Tiomkin",  
      "alternateNames": "Ramat Tiomkin,Ramat Tyomkin,Ramat Tyomqin",
      "latitude": "32.31944",
      "longitude": "34.85083",
      "featureClass": "P",
      "featureCode": "PPLX",
      "countryCode": "IL",
      "cc2": null,
      "admin1Code": "02",
      "admin2Code": null,
      "admin3Code": null,
      "admin4Code": null,
      "population": "0",
      "elevation": null,
      "dem": "43",
      "timezone": "Asia/Jerusalem",
      "modificationDate": "2015-04-08",
      "distance": 0.31574142652299
    }
  ]
  

without 

   {
      "geoNameId": "294071",
      "name": "Netanya",
      "asciiName": "Netanya",
      "alternateNames": "Lungsod ng Ntanya,Natania,Natanya,Nathanya,Netan'ja,Netania,Netanija,Netanja,Netanya,Netánja,Ntanya,na ta neiy,nattaniya,nei tan ya,netaniya,netanya,ntanya,ntnyh,Νετάνια,Нетания,Нетанья,Нетаня,Нетанія,Нетанја,נתניה,نتانيا,نتانیا,நத்தானியா,นาตาเนีย,ネタニヤ,内坦亚,네타냐",
      "latitude": "32.33291",
      "longitude": "34.85992",
      "featureClass": "P",
      "featureCode": "PPL",
      "countryCode": "IL",
      "cc2": null,
      "admin1Code": "02",
      "admin2Code": null,
      "admin3Code": null,
      "admin4Code": null,
      "population": "228204",
      "elevation": null,
      "dem": "38",
      "timezone": "Asia/Jerusalem",
      "modificationDate": "2023-02-07",
      "distance": 1.4216628336859574
    }
  ]

**Comment by tomayac** [comment]
This is most likely a distance calculation issue. What's the latitude/longitude you're querying?

**Comment by tomayac** [comment]
Looks like this is the same core reason as outlined in https://github.com/tomayac/local-reverse-geocoder/issues/83.

**Comment by eligrifel** [comment]
thank you
